//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCrud.DbModels
{
    /// <summary>
    /// Приготовление блюда.
    /// </summary>
    public partial class DishCooking
    {
        /// <summary>
        /// Идентификатор.
        /// </summary>
        public int Id { get; set; }
        
        /// <summary>
        /// Идентификатор блюда.
        /// </summary>
        public int DishId { get; set; }
        
        /// <summary>
        /// Количество блюд.
        /// </summary>
        public int Count { get; set; }
        
        /// <summary>
        /// Время приготовления.
        /// </summary>
        public System.DateTime CookedAt { get; set; }
    
        /// <summary>
        /// Блюдо.
        /// </summary>
        public virtual Dish Dish { get; set; }
    }
}
