//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCrud.DbModels
{
    /// <summary>
    /// Учётная запись пользователя системы.
    /// </summary>
    public partial class UserAccount
    {
        /// <summary>
        /// Идентификатор.
        /// </summary>
        public int Id { get; set; }
        
        /// <summary>
        /// Идентификатор роли пользователя.
        /// </summary>
        public int UserRoleId { get; set; }
        
        /// <summary>
        /// Имя (логин) пользователя.
        /// </summary>
        public string Login { get; set; }

        /// <summary>
        /// Пароль.
        /// </summary>
        public byte[] Password { get; set; }

        /// <summary>
        /// Изображение.
        /// </summary>
        public byte[] Image { get; set; }
    
        /// <summary>
        /// Роль пользователя.
        /// </summary>
        public virtual UserRole UserRole { get; set; }
    }
}
