//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCrud.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDish
    {
        public int DishId { get; set; }
        public string DishName { get; set; }
        public string DishTypeName { get; set; }
        public double DishCookingTimeMinutes { get; set; }
        public double DishWeightGrams { get; set; }
        public Nullable<double> DishCaloricContentPer100Grams { get; set; }
        public Nullable<double> DishPriceRoubles { get; set; }
        public string DishRecipe { get; set; }
        public byte[] DishImage { get; set; }
        public int DishTypeId { get; set; }
    }
}
